@token = eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..xK8wOiZuDZf5g54_.SWh4A3OFO-JKnrjaN1HDHqG9aKWdXMwO5zehQDm8M87pkb9wRJ3djOVsNvqcYGQGJF2Ctc2ZkiNOkeupmTKfBcJLaaCtDnXdrUKfDHahLYw9icMK4bCUgDEGxFR68iOmojGHE6MrBuVUBmpuf9a66fVWQ-md4asfWI27fG-ixYDgwJ6l9J6VMM9cY3s.gokLcP78kPx_ktI4jeVl3g
### GET CHATS
GET http://localhost:3000/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

### 
POST http://localhost:3000/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "message": "Hello World 3"
}

###
@chatId = 5151cf99-8c5a-45dd-867d-4e0ea25965c9

GET http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "message": "Estou testando a API 2"
}

###
@messageId = 0578ef19-eb9d-4c15-b3b6-29bb7a17cf18
GET http://localhost:3000/api/messages/{{messageId}}/events
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/generate-token
Content-Type: application/json

{}